Add landing Page UI
pesto-students/sneaky-snakes pull request #18
Opened 2019-02-19 22:43 UTC by rishabh1403

- Add react router
- setup enzyme
- Add semantic UI
- Add test for Landing Component

2019-02-19 23:53 UTC, rishabh1403 commented
![screenshot from 2019-02-20 05-23-15](https://user-images.githubusercontent.com/10906358/53055975-a7d2de80-34cf-11e9-91f7-fb00cce83c71.png)

2019-02-19 23:54 UTC, rishabh1403 commented
![image](https://user-images.githubusercontent.com/10906358/53056039-d6e95000-34cf-11e9-87dd-fad6cf9f05d7.png)

2019-02-20 14:01 UTC, ravikp7 commented on client/package.json
> +    "test:once": "CI=true react-scripts test",
- I think, the CI environments already set this variable (CI=true), See [Dan Abramov's comment](https://github.com/facebook/create-react-app/issues/1137#issuecomment-279180815)
-  Isn't it already set verbose by react-scripts? 
- Also, if we need to set env variables, I think it's better to use cross-env for Windows support also.

Please let me know your thoughts on this :)

2019-02-20 15:41 UTC, rishabh1403 commented on client/package.json
> +    "test:once": "CI=true react-scripts test",
CI is not for CI clients, it is for husky, test:once, `test` command runs in watchmode and husky ever ends

2019-02-20 16:24 UTC, ravikp7 commented on client/package.json
> +    "test:once": "CI=true react-scripts test",
Great! got it. Thanks for clearing my doubt :)

2019-02-20 17:07 UTC, nimish-gupta requested changes
@rishabh1403 super solid PR, a couple of changes then it LGTM. Highly impressed with abstraction.
Singe question though,
Why you have added tests at a single place instead of at every component level?

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
With this you don't need binding. Have a look at [this](https://hackernoon.com/the-constructor-is-dead-long-live-the-constructor-c10871bea599)
```suggestion
  handleItemClick = (e, { name }) => this.setState({ activeItem: name });
```

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/home/CenterColumn.js
> +
Extra blank line :)

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/home/CenterColumn.js
> +export default CenterColumn;
It's a good abstraction :). You can take this to a next label with center as prop, so then you can align column with whatever property you want.

Also you can just create a boolean prop center and set it to default false, then from the calling site just pass `<AlignColumn center />`

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/home/HugeButton.js
> +);
It's a good abstraction but here again you can provide the link and size ability as prop so that it can be more generic. Like
`<StyledButton huge url />`

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/home/home.css
> +.homePageContainer  .ui.grid{
Try to use [this naming guide](http://getbem.com/introduction/) for css,

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/setupTests.js
> +configure({ adapter: new Adapter() });
Why this thing is required?

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/__tests__/components/home/home.js
> +describe('<Home />', () => {
This block is about home so there is no need of shallowing it again in each call, and if you still want to do then use jest hooks `beforeAll` or `beforeEach`.

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/__tests__/components/home/centerColumn.test.js
> +  it('should render a Column', () => {
This `it` and next `it` are rendering the same message, probably you want to change that :)

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/__tests__/app.test.js
> +describe('<App />', () => {
Use jest hooks `beforeAll` or `beforeEach` for the same functionality.

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/__tests__/components/home/hugeButton.test.js
> +  it('should render a Button', () => {
Use jest hooks `beforeAll` or `beforeEach` for the same functionality.

2019-02-20 17:07 UTC, nimish-gupta commented on client/src/components/common/header.css
> +.container{
Why this thing not along with Header.js ?

2019-02-20 19:45 UTC, rishabh1403 commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
Tried this, ESLINT wouldn't let me use this syntax @nimish-gupta

2019-02-20 19:46 UTC, rishabh1403 commented on client/src/components/home/CenterColumn.js
> +export default CenterColumn;
Got it, love the suggestion :)

2019-02-20 19:46 UTC, rishabh1403 commented on client/src/components/home/HugeButton.js
> +);
got it :+1:

2019-02-20 19:47 UTC, rishabh1403 commented on client/src/setupTests.js
> +configure({ adapter: new Adapter() });
to configure enzyme and to make sure it works with react 16

2019-02-20 19:47 UTC, rishabh1403 commented on client/src/__tests__/components/home/home.js
> +describe('<Home />', () => {
got it :+1:

2019-02-20 19:48 UTC, rishabh1403 commented on client/src/components/common/header.css
> +.container{
@nimish-gupta do you mean to put css in js file ?

2019-02-20 19:53 UTC, rishabh1403 commented
> @rishabh1403 super solid PR, a couple of changes then it LGTM. Highly impressed with abstraction.
> Singe question though,
> Why you have added tests at a single place instead of at every component level?

@nimish-gupta wasn't sure about between the idea of having tests at a single place or component wise...team decided to follow tests at single place following the same dir structure, let me know if otherwise is better

2019-02-20 20:00 UTC, nimish-gupta commented
https://www.reddit.com/r/node/comments/4ipcam/what_is_the_directory_structure_that_you_use_for/
> @nimish-gupta wasn't sure about between the idea of having tests at a single place or component wise...team decided to follow tests at single place following the same dir structure, let me know if otherwise is better

2019-02-20 21:29 UTC, nimish-gupta commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
What's the error it is throwing?

2019-02-20 21:29 UTC, nimish-gupta commented on client/src/setupTests.js
> +configure({ adapter: new Adapter() });
Can you provide link for this?

2019-02-20 21:31 UTC, nimish-gupta commented on client/src/components/common/header.css
> +.container{
like create a Header folder having index.js, header.js and style.css

2019-02-20 21:33 UTC, nimish-gupta commented
> @nimish-gupta wasn't sure about between the idea of having tests at a single place or component wise...team decided to follow tests at single place following the same dir structure, let me know if otherwise is better

We don't have any preference but you can check this [reddit](https://www.reddit.com/r/node/comments/4ipcam/what_is_the_directory_structure_that_you_use_for/) pretty much summarizes our answer.

2019-02-21 15:53 UTC, rishabh1403 commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
![image](https://user-images.githubusercontent.com/10906358/53182151-ed51f180-361e-11e9-9411-7bb230fccced.png)
@nimish-gupta

2019-02-21 15:56 UTC, nimish-gupta commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
Check [this](https://github.com/babel/babel-eslint)

2019-02-21 16:17 UTC, rishabh1403 commented on client/src/setupTests.js
> +configure({ adapter: new Adapter() });
@nimish-gupta https://airbnb.io/enzyme/docs/installation/

2019-02-21 17:20 UTC, nimish-gupta commented on client/src/components/common/alignedColumn/AlignedColumn.js
> +  <Grid.Column textAlign={align || 'left'}>
You don't need this condition as 'left' is already passed in default props

2019-02-21 17:20 UTC, nimish-gupta commented on client/src/components/common/alignedColumn/alignedColumn.test.js
> +  it('should render a Column', () => {
Have a line gap after every block, makes it much more readable :)

2019-02-21 17:20 UTC, nimish-gupta commented on client/src/components/common/header/Header.js
> +  handleItemClick(e, { name }) {
Have you tried using babel-eslint?

2019-02-21 17:24 UTC, rishabh1403 commented on client/src/components/common/Header.js
> +  handleItemClick(e, { name }) {
Done :+1:

2019-02-21 17:28 UTC, rishabh1403 commented on client/src/components/common/alignedColumn/AlignedColumn.js
> +  <Grid.Column textAlign={align || 'left'}>
got it :+1:

2019-02-21 17:32 UTC, rishabh1403 commented
@nimish-gupta Resolved all the issues, please take a look :smile:

2019-02-21 17:33 UTC, nimish-gupta commented on client/src/components/common/styledButton/StyledButton.js
> +
Extra line :( , are you guys using eslint --fix in husky?

2019-02-21 17:45 UTC, rishabh1403 commented on client/src/components/common/styledButton/StyledButton.js
> +
nope, Eslint is not complaining about this

2019-02-21 17:51 UTC, rishabh1403 commented on client/src/components/common/styledButton/StyledButton.js
> +
@nimish-gupta am i missing any eslint config options? Fixed it BTW.

2019-02-21 18:16 UTC, nimish-gupta approved these changes

2019-02-21 18:17 UTC, merged