feat: Add auth pages ui
pesto-students/sneaky-snakes pull request #24
Opened 2019-02-21 18:42 UTC by rishabh1403

Add 
- Sign up Page
- Sign In Page
- Password Reset Page
- Email Verify Page
- Corresponding Tests

Resolves: #23

2019-02-27 18:04 UTC, rishabh1403 commented
![image](https://user-images.githubusercontent.com/10906358/53512124-00196a00-3ae8-11e9-9a55-021b185cb50f.png)
![image](https://user-images.githubusercontent.com/10906358/53512158-0dceef80-3ae8-11e9-95c4-68979f719a40.png)
![image](https://user-images.githubusercontent.com/10906358/53512172-16272a80-3ae8-11e9-8f2d-81a9156f27bf.png)
![image](https://user-images.githubusercontent.com/10906358/53512186-1e7f6580-3ae8-11e9-8f11-1d36f2877e4c.png)
![image](https://user-images.githubusercontent.com/10906358/53512216-2c34eb00-3ae8-11e9-9657-3a33b659e4b8.png)
![image](https://user-images.githubusercontent.com/10906358/53512236-3525bc80-3ae8-11e9-8323-a9be8aa239f6.png)
![image](https://user-images.githubusercontent.com/10906358/53512254-3d7df780-3ae8-11e9-86ac-bc21558fdc35.png)

2019-02-27 21:59 UTC, ravikp7 commented
Looking excellent. Just one question
- Can we get the reset password modal vertically centred on phone view ?
- It seems unreachable to me using one hand.

2019-02-27 22:01 UTC, ravikp7 commented on client/src/app.test.js
>      it('should render two route component', () => {
- This test makes very little sense to me, as we'll be constantly changing this.
- Also, see the description, you seem to forgot to change it from `two` to `five`.

2019-02-27 22:03 UTC, rishabh1403 commented on client/src/app.test.js
>      it('should render two route component', () => {
Yeah, makes sense, maybe we can remove it and add when the pages are done

2019-02-27 22:05 UTC, rishabh1403 commented
> Looking excellent. Just one question
> 
> * Can we get the reset password modal vertically centred on phone view ?
> * It seems unreachable to me using one hand.

sure

2019-02-27 22:18 UTC, rishabh1403 commented
![image](https://user-images.githubusercontent.com/10906358/53526967-a6c33200-3b0b-11e9-953d-e48835a981a7.png)
@ravikp7

2019-02-28 14:57 UTC, nimish-gupta requested changes

2019-02-28 14:57 UTC, nimish-gupta commented on client/src/components/common/InputFields/EmailField.js
> +const EmailField = ({ placeholder }) => (
Why you need this? you can just create Email field by passing `type=email` to the input field

2019-02-28 14:57 UTC, nimish-gupta commented on client/src/components/common/InputFields/PasswordField.js
> +const PasswordField = ({ placeholder }) => (
Why you need this? you can just create Email field by passing `type=password` to the input field

2019-02-28 14:57 UTC, nimish-gupta commented on client/src/components/common/styledButton/StyledButton.js
>      size: size || 'massive',
set this in defaultProps

2019-02-28 14:57 UTC, nimish-gupta commented on client/src/pages/signup/SignUp.js
> +            <EmailField placeholder="Email" />
Just use InputField here with `type=email`

2019-02-28 16:17 UTC, rishabh1403 commented on client/src/components/common/InputFields/EmailField.js
> +const EmailField = ({ placeholder }) => (
InputField has lot more abstractions...EmailField sets up the icon i want, where I want....
If I directly use InputField I will have to pass all the props, which I know won't change for certain field like email or password or number

2019-02-28 16:18 UTC, rishabh1403 commented on client/src/components/common/InputFields/PasswordField.js
> +const PasswordField = ({ placeholder }) => (
same logic as email field

2019-02-28 16:18 UTC, rishabh1403 commented on client/src/components/common/styledButton/StyledButton.js
>      size: size || 'massive',
sure

2019-02-28 16:18 UTC, rishabh1403 commented on client/src/pages/signup/SignUp.js
> +            <EmailField placeholder="Email" />
same logic as in EmailField abstraction

2019-02-28 16:25 UTC, nimish-gupta approved these changes

2019-02-28 16:42 UTC, merged