feat: improve leaderboard api and db queries
pesto-students/sneaky-snakes pull request #30
Opened 2019-02-25 22:33 UTC by ravikp7

fixes:  #29

2019-02-27 21:27 UTC, ravikp7 commented
feat: improve leaderboard api and db queries
 - adds api to query total scores count and limited scores
 - adds api to query a user's rank
 - improve db queries to populate only user's name with score
 - integration tests for the DB with leaderboard APIs

fixes #28 and #29

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/controllers/score.controller.js
> +  const { userId } = req.query;
the userid is coming as params right now, it would make much more sense i guess to move it to query for all get operations, as a variable on routes

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/routes/score.route.js
> +router.get('/rank', getUserRank);
get user id on query
`/rank/:id`
it will help browsers cache it and will follow REST convention

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/routes/score.route.js
> +router.get('/user', getUserScores);
similarly here, add id to query

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/utils/db_score_query.js
>    .find()
better indentation with Score on next line maybe ?

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/utils/db_score_query.js
> +const queryScoresCount = () => Score.countDocuments();
is this synchronous? Don't we need exec here ?

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/utils/db_score_query.js
> +    const greaterScores = await Score.countDocuments({ 'value': { '$gt': score } });
Should we count scores higher than a certain number or scores higher than the number for unique users?

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/utils/db_score_query.js
>      user: userId, value,
split properties across lines :)

2019-02-27 22:31 UTC, rishabh1403 commented on server/src/utils/seed/index.js
> +  await Model.deleteMany();
`deleteMany({})` maybe?

2019-02-27 22:44 UTC, ravikp7 commented on server/src/utils/seed/index.js
> +  await Model.deleteMany();
Actually, I had this query, what does specifying `{}` vs not specifying does?

2019-02-27 23:45 UTC, ravikp7 commented on server/src/utils/db_score_query.js
> +const queryScoresCount = () => Score.countDocuments();
Actually, it gives a thenable object which works with await keyword. Earlier I used exec because I was using Promise instead of `async/ await`, but changed as per feedback.
- `If the value of the expression following the await operator is not a Promise, it's converted to a resolved Promise.` from [Mozilla await docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)
- See [Resolved Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve) also

@nimish-gupta Am I right with my understanding here?

2019-02-27 23:45 UTC, ravikp7 commented on server/src/utils/db_score_query.js
>    .find()
Thanks! will be corrected.

2019-02-27 23:48 UTC, ravikp7 commented on server/src/controllers/score.controller.js
> +  const { userId } = req.query;
It's been already changed from params to query, Am I still missing something?

2019-02-27 23:56 UTC, ravikp7 commented on server/src/routes/score.route.js
> +router.get('/rank', getUserRank);
Looks like I'm still missing something here.
My understanding was:
- `/rank/:id` is called parameters
- `/rank?id=323` is called query

Will learn more on this and update you. Thanks for the `REST convention` part :)

2019-02-27 23:56 UTC, ravikp7 commented on server/src/utils/db_score_query.js
>      user: userId, value,
sure :)

2019-02-28 02:06 UTC, nimish-gupta requested changes

2019-02-28 02:06 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScoresCount.mockImplementation(async () => {
```suggestion
queryScoresCount.mockImplementation(async () => sampleScoresCount())
```

2019-02-28 02:06 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +    const scores = queryScores(parseInt(offset, 10), parseInt(limit, 10));
```suggestion
    const scores = queryScores({ a: parseInt(offset, 10), b: parseInt(limit, 10) });
```
Try to use ^pattern for passing arguments. 
Pros: you will know what are the arguments name from the calling itself and also you don't have to remember the function position also

2019-02-28 02:06 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +    const data = await Promise.all([scores, totalScores]);
is totalscores sum of all scores? If yes then why db query you can just calculate at run time. Also instead of `data` use scores as variable name, because data is very generic name.

2019-02-28 02:06 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +    res.status(HTTP_SUCCESS_OK).json(data);
Instead of passing array try to pass the object, because keys give more info then indexes :)

2019-02-28 03:28 UTC, ravikp7 commented on server/src/controllers/score.controller.js
> +    const data = await Promise.all([scores, totalScores]);
- It's total number of scores present in the collection, so that we can figure out how many number of pages we require for leaderboard scores. And obviously it'd be limited on the website, like only the first 100 entries will be shown.
- It was resolving a specified number of documents (using `offset` and `limit`) in `scores` and total number of scores in `totalScores`, so combined both I referred to them as `data`. Still needs change?

2019-02-28 03:30 UTC, ravikp7 commented on server/src/controllers/score.controller.js
> +    res.status(HTTP_SUCCESS_OK).json(data);
I didn't get your point here. If you're talking about `array` in `Promise.all`, then I was resolving two promises here, I'm clueless about how to use object here. Can you please elaborate more?

2019-02-28 03:32 UTC, ravikp7 commented on server/src/controllers/score.controller.js
> +    const scores = queryScores(parseInt(offset, 10), parseInt(limit, 10));
Thanks for this excellent suggestion :)

2019-02-28 03:38 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScoresCount.mockImplementation(async () => {
- `sampeScoresCount` is a number, `not a function`
- Here, I'm trying to mock DB query which returns a thenable object resolving to a number
- If I didn't get you right, please explain more?

2019-02-28 03:54 UTC, ravikp7 commented on server/src/utils/db_score_query.js
> +    const greaterScores = await Score.countDocuments({ 'value': { '$gt': score } });
Thanks for this great point out. I'll modify the query as well as tests for this.

2019-02-28 14:16 UTC, rishabh1403 commented on server/src/routes/score.route.js
> +router.get('/rank', getUserRank);
maybe I am wrong on naming, will look into it, but I meant `/rank/:id`

2019-02-28 14:52 UTC, nimish-gupta requested changes

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScoresCount.mockImplementation(async () => {
```suggestion
queryScoresCount.mockImplementation(async () => sampleScoresCount)
```

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +    const data = await Promise.all([scores, totalScores]);
Ok so please change the variable name to `scoresCount` or something similar

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +    res.status(HTTP_SUCCESS_OK).json(data);
```suggestion
    const toSend = {scores: data[0], scoresCount: data[1]}
```

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
>    } catch (error) {
Create a wrapper around it, so you don't have to send the same status, error every time like
```suggestion
 const sendResultOrError = async ({ query, res, successStatus = HTTP_SUCCESS_OK, errorStatus = HTTP_INTERNAL_SERVER_ERROR}) => {
   try {
       const result = await query;
       res.status(successStatus).json(result);
   } catch (error) {
       res.status(errorStatus).json({ error })
   }
 }
```
Then you can use with every api call like
```suggestion
  return sendResultOrError({ query: queryRank(userId), res })
```

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/utils/db_score_query.js
> +const queryScoresCount = () => Score.countDocuments();
Check [this](https://lorefnon.tech/2018/06/09/javascript-async-await-with-arbitrary-thenables/)

2019-02-28 14:52 UTC, nimish-gupta commented on server/src/utils/db_score_query.js
> +    throw error;
You don't have to catch an error to throw it in the end, just use this function without try catch, if you don't want to handle the error

2019-02-28 14:57 UTC, rishabh1403 commented on server/src/utils/seed/index.js
> +  await Model.deleteMany();
There is no different as per output is concerned, it's just to make it more consistent

2019-02-28 16:06 UTC, ravikp7 commented on server/src/controllers/score.controller.js
>    } catch (error) {
@nimish-gupta That seems like a really good way to refactor.
- But I think that'd increase complexity as we've only two controllers having the same functionality.
- I think the code is more readable now than changes you suggest.
- As, we'd have to look another function to understand the controller functionality just for two controllers out of total four.
- According to me, the changes you suggest would make more sense when we've more than two controllers having same functionality.

I maybe wrong, Please let me know your thoughts on this :)

2019-02-28 16:13 UTC, ravikp7 commented on server/src/utils/seed/index.js
> +  await Model.deleteMany();
@rishabh1403 Sorry, I didn't get you on this. Can you please elaborate on `consistent`?

2019-02-28 16:30 UTC, ravikp7 commented on server/src/utils/db_score_query.js
> +const queryScoresCount = () => Score.countDocuments();
Thanks @nimish-gupta 
- I think, now it makes more sense to remove exec() as we want to query DB everytime, which isn't the case otherwise with `Promise` since it's resolved once.

2019-02-28 20:22 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
>    } catch (error) {
This will be not specific to score controller only but it can be used with all the request's responses.

2019-02-28 20:29 UTC, ravikp7 commented on server/src/controllers/score.controller.js
>    } catch (error) {
But, there are also other controller specific things going on in the `try block`. How can I wrap it then?
- Do you mean do all those stuff in a `try` block and call this `sendResultOrError` function in that try block?

2019-02-28 21:59 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
>    } catch (error) {
```suggestion

const sendResultOrError = async ({ query, res, errorStatus = HTTP_INTERNAL_SERVER_ERROR}) => {
   try {
       const result = await query;
       return result;
   } catch (error) {
       res.status(errorStatus).json({ error })
   }
 }
```

2019-03-01 15:32 UTC, rishabh1403 commented on server/src/utils/seed/index.js
> +  await Model.deleteMany();
deleteMany({}) vs deleteMany()... on line 50 and 54 same function is used but different style...it's not consistent

2019-03-01 15:35 UTC, rishabh1403 approved these changes

2019-03-01 15:35 UTC, rishabh1403 commented
LGTM

2019-03-01 15:38 UTC, merged