[WIP]: leaderboard db schema and api
pesto-students/sneaky-snakes pull request #8
Opened 2019-02-13 23:54 UTC by ravikp7

2019-02-18 23:48 UTC, ravikp7 commented
- Add APIs to get individual user scores, scores in a range and save score
- Add DB schema and queries for operations
- Tests for DB schema and route controllers

fixes #12

2019-02-18 23:50 UTC, ravikp7 commented
`CI is not added yet, so attaching screenshot for passing tests` Will be adding CI next
![screenshot from 2019-02-19 05-17-34](https://user-images.githubusercontent.com/13567359/52981446-dab0a000-3405-11e9-9716-b1d638b4b52f.png)

2019-02-18 23:51 UTC, ravikp7 commented
- DB query tests are not implemented yet as it's dependent on DB setup and config which are to be implemented by @adityasmksaxena 
- Will be adding after that

2019-02-18 23:55 UTC, ravikp7 commented
Tested the DB with own server/index.js file with changes which I've not committed here

2019-02-19 12:05 UTC, nimish-gupta requested changes
@ravikp7 have you guys setup the eslint on the server side?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/contants');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../controllers/score.controller');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/db_score_query');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryUserScore.mockImplementation(userId => new Promise(
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +insertScore.mockImplementation((userId, value) => new Promise(
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +      function json(data) {
arrow functions?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +    it('should call db function with range', async () => {
You can use `beforeEach` hook to call `getScores` for every success request and keep that in describe block. A separate describe block for every invalid request and a beforeEach hook.

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/utils/db_score_query.js
> +  // https://mongoosejs.com/docs/promises.html#queries-are-not-promises
👍

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +  return queryScores(parseInt(range, 10))
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +  return queryUserScore(userId)
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +  return insertScore(userId, value)
Why not `async/await`?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +const scoreDbQuery = require('../utils/db_score_query');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/controllers/score.controller.js
> +} = require('../utils/contants');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/models/score.model.js
> +const mongoose = require('mongoose');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/routes/score.route.js
> +const scoreController = require('../controllers/score.controller');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/routes/score.route.js
> +const express = require('express');
why not import statements?

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/models/score.model.test.js
> +describe('leaderboard schema validation', () => {
Its good that you are checking the schema validation, love the way that how you tested, but it seems that these are overkill over here because schema is provided by mongoose library and you are using functions provided by mongoose itself, and you are not creating any of your own function so basically you are checking mongoose functionality which is already tested by the library mongoose itself, so basically you don't need these tests here.

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +    it('should call db function with userID', async () => {
You can use `beforeEach` hook to call `getScores` for every success request and keep that in describe block. A separate describe block for every invalid request and a beforeEach hook.

2019-02-19 12:05 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +    it('should call db function with userId and value', async () => {
You can use `beforeEach` hook to call `getScores` for every success request and keep that in describe block. A separate describe block for every invalid request and a beforeEach hook.

2019-02-19 13:48 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/contants');
Since, the current Node LTS doesn't support import/export and we didn't setup Babel, so went with it. I understand the advantages of using import/export and once support is there, we can just drop the Babel transpilation. Will add webpack and babel

2019-02-19 13:52 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
There, in that function, I had to `return a promise which resolves or rejects based on a conditional`. I'm not sure how using `async/await` can make it better. Can you please elaborate more?

2019-02-19 13:57 UTC, ravikp7 commented on server/src/__tests__/models/score.model.test.js
> +describe('leaderboard schema validation', () => {
The intention was to ensure that in the schema definition, the field is set to required. As, it's very easy to miss that required in the field. Will it be still an overkill? Let me know your thoughts :)

2019-02-19 14:03 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +      function json(data) {
I'd to bind that function, so my first approach was to use normal function and bind that. I didn't realize that arrow functions are there for this purpose. Will replace it with arrow function now. Thank you :)

2019-02-19 14:13 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
```suggestion
queryScores.mockImplementation(async (range) => {
    if (range) {
        return range
    }
    throw new Error('Range not defined')
})
```

2019-02-19 14:16 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +    it('should call db function with range', async () => {
I thought of testing all the functionality of single controller in a single describe block. Though haven't really used `beforeEach` before, will definitely try to use it next time. Thanks :)

2019-02-19 14:17 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/contants');
ok good call for that.
Please add babel for latest ES features, why you need webpack?

2019-02-19 14:18 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/contants');
Yes, eslint is setup with the airbnb config

2019-02-19 14:49 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +} = require('../../utils/contants');
> ok good call for that.
> Please add babel for latest ES features, why you need webpack?

I thought we need webpack is required for babel transpilation with nodemon. Checked it now, it isn't the case. Thank you :) :100:

2019-02-19 15:00 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
I wasn't aware of this `Implicit Promise` behaviour of async functions. Thanks for this :+1:

2019-02-19 16:40 UTC, nimish-gupta commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
Check [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)

2019-02-19 18:43 UTC, ravikp7 commented
`Tests Screenshot`
![screenshot from 2019-02-20 00-04-46](https://user-images.githubusercontent.com/13567359/53039053-3b8eb580-34a4-11e9-87e1-0719b4336117.png)

2019-02-19 18:48 UTC, ravikp7 commented
Fixed in this pull request after review:

`First Commit`
- Added babel for server

`Second Commit`
- Used es6 import/export instead of require
- Replaced the bound function with arrow one
- Used `beforeEach` for each controller using separate describe blocks for `SUCCESS` and `FAILURE`

2019-02-19 19:09 UTC, ravikp7 commented on server/src/__tests__/controllers/score.controller.test.js
> +queryScores.mockImplementation(range => new Promise(
Yes, had already checked it, thanks :+1:

2019-02-19 21:59 UTC, nimish-gupta commented
@ravikp7 you can replace `.then` with `async/await` syntax in your code.

2019-02-19 22:50 UTC, ravikp7 commented
> @ravikp7 you can replace `.then` with `async/await` syntax in your code.

@nimish-gupta done :+1:

2019-02-19 22:53 UTC, nimish-gupta approved these changes
LGTM 3>

2019-02-19 23:19 UTC, merged