[wip]: add server side authentication
pesto-students/sneaky-snakes pull request #9
Opened 2019-02-14 18:44 UTC by adityasmksaxena

[x] - add db support to save and retrive users
[] - create api (signin, signup & user)
[] - add token workflow

2019-02-18 15:40 UTC, ravikp7 commented on server/.eslintrc.js
> +const eslintRules = {
There's already a eslint config file?

2019-02-18 15:46 UTC, ravikp7 commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
Are you sure eslint is showing no errors? as you've used double quotes for string in a lot of places .

2019-02-18 16:13 UTC, adityasmksaxena commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
I extended prettier to eslint config file and double quotes are default for me.

2019-02-18 16:14 UTC, adityasmksaxena commented on server/.eslintrc.js
> +const eslintRules = {
I renamed it with ".js" extension.

2019-02-18 16:32 UTC, rishabh1403 commented on server/.eslintrc.js
> +const eslintRules = {
please don't change eslint config until you have strong reason for it, extending prettier and allowing double quotes....i am not sure it's a good idea...let's wait for mentor's review

2019-02-18 16:32 UTC, rishabh1403 commented on server/src/config/config.json
> +  "test": {
why not a js file with exports ?

2019-02-18 16:32 UTC, rishabh1403 commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
wait hold for review from mentors on this

2019-02-18 16:37 UTC, adityasmksaxena commented on server/src/config/config.json
> +  "test": {
done.

2019-02-18 16:44 UTC, adityasmksaxena commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
There were conflicts between eslint and prettier rules and hence I needed to extend prettier in eslint config file to make them work together.

2019-02-18 16:48 UTC, adityasmksaxena commented on server/.eslintrc.js
> +const eslintRules = {
There were conflicts between eslint and prettier rules and hence to make them work together I needed to extend prettier in eslint config file.

2019-02-18 17:15 UTC, nimish-gupta commented
@adityasmksaxena Please remove WIP after assigning it for review.

2019-02-18 17:41 UTC, andrewlinfoot commented on server/.eslintrc.js
> +const eslintRules = {
this is right. you need to add the eslint prettier config which tells eslint to ignore all rules that are handled by prettier

2019-02-18 18:08 UTC, nimish-gupta requested changes

2019-02-18 18:08 UTC, nimish-gupta commented on server/.eslintrc.js
> +const eslintRules = {
So question what will happen if there is a property which is true in eslint but false in prettier will work, then which property will override?
I think we should strict to airbnb rules for styling and should override the properties of prettier which are conflicting with eslint.
You can use [prettier-eslint](https://github.com/prettier/prettier-eslint) package to enforce eslint fixes are applied after prettier changes. You can add this check for staged files.

2019-02-18 18:08 UTC, nimish-gupta commented on server/.prettierrc.js
> +  trailingComma: "es5",
Here you can add property `single-quote: true` for strings to use single quotes

2019-02-18 18:08 UTC, nimish-gupta commented on server/package.json
> +    "eslint-config-prettier": "^4.0.0",
Basically this package overrides the eslint rules for prettier rules, as it takes the last entry in the eslintrc extends property and overrides other one.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/config/config.js
> +    MONGODB_URI: "mongodb://localhost:27017/SneakySnakesTest",
Please use these as env variables instead of hardcoding here, as this will help other members to use their own config urls.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/config/config.js
> +    JWT_SECRET: "lskjf923io=-lksdjflsk9323n",
Never commits secrets to a source control.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/config/config.js
> +    MONGODB_URI: "mongodb://localhost:27017/SneakySnakesTest",
You can always set default properties to local.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/config/index.js
> +  });
Please don't mutate process.env, you can always create a config file and read env variables from there. 
Check these articles [1](https://medium.freecodecamp.org/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a) and [2](https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786) for managing the envs.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
There is always a way to change the default rule :)

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/auth.js
> +      .header("x-auth", token)
Please adhere to the eslint-airbnb styling guides only

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/auth.js
> +    return res.status(400).send();
You are not sending any error here, the user will not know what the issue was.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/user.js
> +    return res.status(400).send();
You are not sending any error here, the user will not know what the issue was.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/user.js
> +    return res.status(400).send();
You can add a wrapper for all the requests that will send error when there is error with error and status code

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/db/mongoose.js
> +const dbUrl = process.env.MONGODB_URI;
Please import env variables from a common place, check [this](https://stackoverflow.com/a/48828102/10322565) for further info

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/controllers/auth.js
> +    const user = await User.create({ name, email, password });
What will happen if the user with email already exists? (I am supposing that email is primary key over here)

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/middleware/authenticate.js
> +        return Promise.reject();
How client will know that why he/she is not authenticated?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +  tokens: [
Can you please explain this part of schema?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +  // eslint-disable-next-line no-underscore-dangle
why?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +    decoded = jwt.verify(token, process.env.JWT_SECRET);
Please import env variables from a common place, check [this](https://stackoverflow.com/a/48828102/10322565) for further info

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +    return Promise.reject();
You are not sending any error here, the user will not know what the issue was.

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +  const { _id } = decoded;
why dangling pointer?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +    return Promise.reject();
Why? you can throw an error simply over here

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +    bcrypt.compare(password, user.password, (err, res) => {
why not `async/await`?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/models/user.js
> +    return Promise.reject();
Why are you catching an error? If in the end you are just rejecting it?

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/server.js
> +    const port = process.env.PORT;
Please import env variables from a common place, check [this](https://stackoverflow.com/a/48828102/10322565) for further info

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/server.js
> +app.use("/api/users", userRouter);
This will become more and more complex once you have more routes, you can split it into diff file. :)

2019-02-18 18:08 UTC, nimish-gupta commented on server/src/middleware/authenticate.js
> +        return Promise.reject();
Why not `async/await` ?

2019-02-18 18:18 UTC, nimish-gupta commented
@adityasmksaxena tests?????????

2019-02-18 18:40 UTC, adityasmksaxena commented on server/src/controllers/auth.js
> +    const user = await User.create({ name, email, password });
yes, email is set to be a unique field in UserSchema. So if the user with email exists then MongoDB will throw an Error.

2019-02-18 18:49 UTC, adityasmksaxena commented on server/src/models/user.js
> +  tokens: [
I think you are asking for the tokens array part of the UserSchema.
Tokens is an array of token objects.
Each token object has field "access" which is set to "auth" for authentication related token but can be set to "resetPassword" or "emailVerification" etc as per design.
Each token object also has field "token" to store the actual token created using jwt and some secret key.

2019-02-18 18:52 UTC, adityasmksaxena commented on server/src/models/user.js
> +  // eslint-disable-next-line no-underscore-dangle
could be named better but my thinking was to use _id because that is what is being used.

2019-02-18 18:53 UTC, adityasmksaxena commented on server/src/models/user.js
> +  const { _id } = decoded;
I'll rename it to "id"

2019-02-18 18:58 UTC, adityasmksaxena commented on server/src/server.js
> +app.use("/api/users", userRouter);
not sure about what can go in diff file here.

2019-02-18 19:01 UTC, adityasmksaxena commented on server/src/models/user.js
> +    bcrypt.compare(password, user.password, (err, res) => {
not sure how to use async/await here. bcrypt works on a callback. I wrapped the bcrypt.compare function call in promise to use await in the controller.

2019-02-18 19:03 UTC, adityasmksaxena commented on server/src/models/user.js
> +    return Promise.reject();
I understand it. It is a mistake.

2019-02-18 19:42 UTC, adityasmksaxena commented on server/.prettierrc.js
> +  trailingComma: "es5",
done

2019-02-18 21:16 UTC, nimish-gupta commented on server/src/models/user.js
> +    bcrypt.compare(password, user.password, (err, res) => {
Check node [promisfy](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original)

2019-02-19 19:38 UTC, nimish-gupta commented on server/src/models/user.js
> +  const { _id } = decoded;
Mongoose also create a id field you can use that.

2019-02-19 20:11 UTC, adityasmksaxena commented on server/src/models/user.js
> +    return Promise.reject();
corrected.

2019-02-19 20:11 UTC, adityasmksaxena commented on server/src/models/user.js
> +    bcrypt.compare(password, user.password, (err, res) => {
done. thanks.

2019-02-19 20:23 UTC, adityasmksaxena commented on server/src/models/user.js
> +  const { _id } = decoded;
read about it and corrected. thanks.

2019-02-19 21:47 UTC, adityasmksaxena commented on server/src/server.js
> +    const port = process.env.PORT;
done.

2019-02-19 22:09 UTC, adityasmksaxena commented on server/src/config/config.js
> +    JWT_SECRET: "lskjf923io=-lksdjflsk9323n",
thanks. created a .env file which will not be committed to Github and will contain all required variables.

2019-02-19 22:10 UTC, nimish-gupta requested changes
Add babel to support import/export syntax instead of require syntax :)

2019-02-19 22:10 UTC, nimish-gupta commented on server/src/models/user.js
> +  // eslint-disable-next-line no-underscore-dangle
You can remove this line

2019-02-19 22:10 UTC, nimish-gupta commented on server/src/models/user.js
> +  const user = this;
Try to be less dependent on the hooks, because this will lead to hidden problems, like this doesn't tell the actual flow of the program, instead of add a hook you can just create a function and call it from the sign up by this you will know that password comparison is happening before saving the data.

2019-02-19 22:43 UTC, adityasmksaxena commented on server/src/models/user.js
> +  const user = this;
The only thing I can think about is that I'll have to manually check password string length which is handled by mongoose schema at present. Also, I'll have to hash the password on password reset.

2019-02-24 14:52 UTC, nimish-gupta commented on server/src/models/user.js
> +  const user = this;
```suggestion
  const hashPassword = (user) => {
     if (!user.isModified('password') {
        return user;
     }
     try {
        const hash = await bcrypt.hash(user.password, 10);
        user.password = hash;
     } catch (error) {
        throw new Error('unsuccessful hashing password');
     }
     return user;
  }
```

2019-02-24 14:52 UTC, nimish-gupta commented on server/src/__tests__/routes/auth.js
> +    // console.log(fullUrl);
remove console.log

2019-02-25 14:38 UTC, ravikp7 commented on yarn.lock
> +  version "5.1.0"
- Have you updated the root `package.json` also?
- If not, any reasons for updating root `yarn.lock` ?

2019-02-26 01:47 UTC, adityasmksaxena commented on server/src/models/user.js
> +  const user = this;
done :). thanks.

2019-02-26 01:58 UTC, adityasmksaxena commented on yarn.lock
> +  version "5.1.0"
It must have been a mistake. I'll keep this in mind.

2019-02-26 12:28 UTC, nimish-gupta reviewed
Looks good PR, feel free to merge after these little tweaks 👍

2019-02-26 12:28 UTC, nimish-gupta commented on server/src/controllers/auth.js
> +    if (!email || !password) {
This will be thrown by mongoose itself as these are marked as required

2019-02-26 12:28 UTC, nimish-gupta commented on server/src/routes/auth.db.test.js
> +beforeAll(async () => {
Use jest teardown, setup and environment files for one-time setup, as starting server will be required in all the db tests

2019-02-26 12:28 UTC, nimish-gupta commented on server/src/routes/auth.db.test.js
> +    done();
why done?

2019-02-26 13:41 UTC, adityasmksaxena commented on server/src/routes/auth.db.test.js
> +    done();
my mistake.

2019-02-26 13:46 UTC, adityasmksaxena commented on server/src/routes/auth.db.test.js
> +beforeAll(async () => {
will do it in a separate PR.

2019-02-26 13:48 UTC, merged